### ISSUE TITLE
Unable to get property 'add' of undefined or null reference

### ISSUE THREAD

**Issue by joeybaker** [jeffbski/joi-browser#11]
We've been running joi-browser in prod for quite sometime, and it works great … except in IE 10 :\

![](https://cloudup.com/cCRqKn92F59+)

**Comment by jeffbski** [comment]
That's really strange. Do you know why it technically has problems in IE 10?

Is there something we could polyfill to fix it?

**Comment by joeybaker** [comment]
I have _no clue_! I've found this really odd, and can't see why IE would be different, but I haven't spent a ton of time digging into it.

**Comment by joeybaker** [comment]
Whoops… I dug into the logs more, and found some instances where IE9 is affected to. A polyfill is likely the answer, I just don't know _what_ to polyfill.

**Comment by joeybaker** [comment]
Edit: maybe https://github.com/hapijs/joi/blob/b252ea9efe66d622801cb9b7cb543c6e87718958/lib/any.js#L847 is the root cause? Maybe we need a shim for `Buffer`?

**Comment by jeffbski** [comment]
That's certainly worth a try.

**Comment by Marsup** [comment]
Unlikely considering the error. It didn't even manage to create the set (not the JS set, our internal set). Seems unlikely considering what it's doing.

**Comment by Marsup** [comment]
Assuming it's still true, I'd say you're suffering from http://ricostacruz.com/til/babel-ie-class-inheritance.

**Comment by joeybaker** [comment]
@Marsup that sounds like a likely candidate!

**Comment by joeybaker** [comment]
Just following up: #12 seems to have fixed this issue. Thanks @Marsup!
