### ISSUE TITLE
Uncaught ReferenceError: Joi is not defined

### ISSUE THREAD

**Issue by fabiobon** [jeffbski/joi-browser#2]
Sorry, could you create a sample of integration in browser?
Thanks

**Comment by fabiobon** [comment]
SOLVED: There's an error inside (webpack.config.js)
  output: {
    libary: 'Joi',

**Comment by jeffbski** [comment]
Yes, I need to create an example for use. The webpack.confg.js is what I use to build the package which gets uploaded to npm, not what you would use to consume it in your app. So I need to provide a nice example of how people consume this from webpack and browserify.

Thanks for the issue.

**Comment by jeffbski** [comment]
I added some usage information to the README to help people in using joi-browser.
