### ISSUE TITLE
IE11-: Symbol is undefined

### ISSUE THREAD

**Issue by igorescobar** [jeffbski/joi-browser#22]
This is how my package.json looks like:
```
...
  "joi": "10.6.0",
  "joi-browser": "10.6.0",
....
  "browser": {
    "joi": "joi-browser"
  },
```
And this error occurs when on IE11 and older browsers. EDGE/Chrome/Firefox/Safari works fine.

<img width="699" alt="screen shot 2017-07-14 at 13 30 11" src="https://user-images.githubusercontent.com/24032/28212278-98bd55ba-6898-11e7-894a-73c443c551a0.png">

Any idea on how to solve this?

**Comment by igorescobar** [comment]
Thanks but turned out that I was requiring the `require('babel-polyfill');` on the wrong place... right after I was requiring joy etc so it raised this exception.

Thanks!

**Comment by elyobo** [comment]
What is the target env for this package?  We use `transform-runtime` rather than the polyfill, so this is giving us some grief.

**Comment by elyobo** [comment]
Ended up switching back to joi and using the config from this repo with the addition of `transform-runtime` to get it working.  Had to drop drop down to joi 10.2.2 to find a version that wasn't using `Array.prototype.find` as well.  Perhaps both of these issues should be mentioned as things that require polyfilling?
