### ISSUE TITLE
Github Releases + Bower

### ISSUE THREAD

**Issue by HQarroum** [jeffbski/joi-browser#23]
I would like to know if you have planned to register this project on Bower? My suggestion would be to use Travis to compile the assets and push them into Github Releases on each new release.

This way Bower users would be at least able to use `joi-browser` even if you do not commit the dist/ folder in your repository.

**Comment by jeffbski** [comment]
Thanks for asking. I hadn't really planned on registering on Bower, it seems that the majority seems to have moved away from that tool. 

However since you can get all of the built packages through unpkg.com (which exposes things on npm), I believe that you can install using a URL with bower. 

`bower install https://unpkg.com/joi-browser@10.6.1/dist/joi-browser.min.js`

This URL shows you all the various files that are distributed
https://unpkg.com/joi-browser@10.6.1/dist/

You can use a variety of version matchers in the URL to get exactly what you want. You can see the readme https://unpkg.com/#/

Does this work for you?

**Comment by HQarroum** [comment]
I agree that Bower is getting less traction, and less people are using in _new_ projects. I also agree that using `unpkg` would be a good solution for that, and yes it works for me.

We however lose semver native integration with bower (e.g `joi-browser#10.0.5`), but that would also be the case when used with Github Releases URLs anyway.

I'll definitely also drop `Bower` support for open-source projects given the pain it is to properly deploy compiled assets since it does not feature a backend repository like `npm` does.

Thanks for your response!

**Comment by jeffbski** [comment]
You can do some of the standard semver matching with unpkg.com so instead of using joi-browser#10.0.5 you can use forms like joi-browser^10.0.5. See the docs for all the forms they support.

**Comment by HQarroum** [comment]
Sure, however Bower won't support semver on `unpkg` resources if there are for instance concurrent `joi-browser` versions used by submodules of the project. The URL is opaque to Bower in the `dependencies` list.

Another disadvantage I see to using `unpkg` compared to Github Releases, is that it is not possible to retrieve the project archive containing the library *and* the `package.json` or `bower.json`. As of today, `joi-browser` is not declaring any dependency, but in the future how would Bower resolve `dependencies` without the `bower.json` ? With Github Releases, the whole project archive is downloaded, so it is fine.

Any ideas ?

**Comment by jeffbski** [comment]
I wonder if there is a general solution for bower users that helps with the transition to npm? 

I think you can request the package.json from unpkg using a separate request, so maybe there is a helper library that can request both and then use that to fetch dependencies??

**Comment by HQarroum** [comment]
I've been looking to a solution with `unpkg`, and to my surprise didn't find anything really efficient to package all the project using a single unpkg.com URL in the dependency list. There is [bower-npm-resolver](https://github.com/mjeanroy/bower-npm-resolver), but it depends of course on npm to install the bower resolver, and that isn't always desirable.

Best solution I came for using bower is Github Releases. Some people uses npm and bower, and at the build stage merge some dependencies, but that's more a hack than a solution.
