### ISSUE TITLE
Hoek problem when using max(joi.ref('someValue'), 'utf8')

### ISSUE THREAD

**Issue by ChrispCode** [jeffbski/joi-browser#24]
I tried to use the joi.max with ref inside and an error occure:
```
Buffer.isEncoding is not a function
    at _class.eval [as max] (eval at ./node_modules/joi-browser/dist/joi-browser.js 
```
I think it has something to do with Hoek, I tried installing it, but it also didn't work!

**Comment by jeffbski** [comment]
@ChrispCode if you want to add a test to https://github.com/jeffbski/joi-browser/blob/master/src/basic.kmocha.js then I can try to resolve and make sure it stays working. PR is welcome or just provide the code and I can create.

**Comment by ChrispCode** [comment]
@jeffbski I was able to go around this. I converted the values to numbers and then the utf8 encoding was unnecessary. Everything worked fine!

**Comment by jeffbski** [comment]
@ChrispCode thanks for following up. I'm glad you found a way to go forward. I'll close this but will keep the working on the buffer issue to see if we can figure out the issue. Might just need to upgrade webpack and babel.
