### ISSUE TITLE
Assocated input attributes

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [jeffbski/joi-browser#31]
It would be nice to get the associated input attributes so that they could also be applied to the input element in case javascript is disabled.

Is there a way to get a list of the applied checks,
```javascript
Joi.string().email().GET_CHECKS()
// ['string', 'email']
```

so that they could be mapped to html attributes to be added to the input?

**Comment by jeffbski** [comment]
@BebeSparkelSparkel That seems like a reasonable idea. Could you post that over on the main Joi repo so the main Joi developers could consider adding it? 

You can post over at https://github.com/hapijs/joi

Then it will flow down to this project after they add it to a future version of Joi.

**Comment by BebeSparkelSparkel** [comment]
Sure
