### ISSUE TITLE
Numeric fields accepting invalid numeric values...

### ISSUE THREAD

**Issue by sipi41** [jeffbski/joi-browser#40]
I'm a newbie, learning React. I'm using joi-browser with Chrome. I created a basic numeric input with an onchange event validator and created my schema, but when I test on my browser, I can't enter letters but I can enter "eeeee" or "-----" and it display no errors at all, of course I know this is not a valid number but it seems not to be detected by joi-browser.  It works fine if I enter e20 or xyz...

Is there a way to fix this situation? I sent a message to Joi but they referred me here for help, meanwhile they mentioned something about "**joi 14**" as follow: 

> _joi-browser should probably be updated with joi 14, you can submit a PR on their repo to help the maintainer move forward._

**Comment by nirav7707** [comment]
can you copy your schema in the comment section?

**Comment by sipi41** [comment]
thanks for your answer.... sorry, I left React, now I'm going to Blazor,  thank you anyway.
