### ISSUE TITLE
Joi-browser inport not working.

### ISSUE THREAD

**Issue by NicTanghe** [jeffbski/joi-browser#42]
#### Context

* *node version*: 6.10.2
* *joi version*: joi-browser@13.4.0
* *environment* (node, browser): node vscode react firefox
* *used with* (hapi, standalone, ...): standalone (i think)
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce ?

 Import joi-browser with the following code

`import Joi from "joi-browser"`

The folder with the files are in node modules.

#### Which result you had ?

vscode returns the following error.

```
module "c:/Users/nicta/Documents/dev/React/vidly/node_modules/joi-browser/dist/joi-browser"
Could not find a declaration file for module 'joi-browser'. 'c:/Users/nicta/Documents/dev/React/vidly/node_modules/joi-browser/dist/joi-browser.js' implicitly has an 'any' type.
  Try `npm install @types/joi-browser` if it exists or add a new declaration (.d.ts) file containing `declare module 'joi-browser';`ts(7016)
```

on my webapp i get the following error.

```
TypeError: joi_browser__WEBPACK_IMPORTED_MODULE_3___default.a.String is not a function
LoginForm
C:/Users/nicta/Documents/dev/React/vidly/src/Components/common/loginForm.jsx:13

  10 | 
  11 |  schema = {
  12 |    username: Joi.string().required(),
> 13 |    password: Joi.String().required()
  14 |  };
  15 | 
  16 |  username = React.createRef();
```

#### What did you expect ?

for evrything to work.

**Comment by NicTanghe** [comment]
Note adding the .d.ts file only removes the error in vscode not in the browser.

**Comment by NicTanghe** [comment]
var Joi = require("joi-browser"); also doesnt work and returns the following error in browser.

TypeError: Joi.String is not a function

**Comment by NicTanghe** [comment]
i ws being stupid i capitalised the s in the Joi.string()

**Comment by AlmTalal** [comment]
Hello Nic, I have the same error, how did you solve it ?
