### ISSUE TITLE
Extend function missing

### ISSUE THREAD

**Issue by jmsegrev** [jeffbski/joi-browser#6]
For some reason, new extend function in Joi 9.0.0 is not defined in the Joi build. For the npm published package.

**Comment by jeffbski** [comment]
@jmsegrev Thanks for reporting this. I'll take a look and see if I can figure out why that is missing.

**Comment by jmsegrev** [comment]
@jeffbski To update, it just seams that the build of the actual npm version is still on an older one (berfore Joi 9.0.0). I cloned the repo and after running the build, everything is working fine. Right now I'm using my fork, but will like to use the one from npm.

**Comment by jeffbski** [comment]
@jmsegrev I guess I had updated the package.json but hadn't updated the actual module before building. Well anyway, I have updated to 9.0.1 (and updated the package this time) and published to npm. Let me know if this new version is ok. Thanks.

**Comment by jmsegrev** [comment]
@jeffbski Everything is ok, thanks.
